# I wouldn't recommend setting this to more than 150.
# Past that, and the server starts crashing. Badly.
max-reach-distance: 100

# Choose either FALLING_BLOCK, MAGMA_CUBE, SHULKER, or STRUCTURE_BLOCK.
# Each has disadvantages.
# FALLING_BLOCK   : if falling-block-type is same as targeted, a whole lot of client issues happen
# MAGMA_CUBE      : shakes and jitters; can't interact with blocks up close
# SHULKER         : you can see lil shulker guy in the middle of non-full blocks
# STRUCTURE_BLOCK : may override other blocks; can be seen by player; cannot change color
highlighter: SHULKER

# Only works with FALLING_BLOCK highlighter.
falling-block-type: GLASS
