name: BuildersReach
description: Build from afar.
authors: [ TehBrian ]
website: https://github.com/TehBrian/BuildersReach

version: ${version}
main: xyz.tehbrian.buildersreach.BuildersReach
api-version: 1.17

commands:
  buildersreach:
    description: Various commands for BuildersReach.
    aliases: [ br ]
    
permissions:
  buildersreach.use:
    permission: Permission to turn on BuildersReach for self.
    default: true
  buildersreach.reload:
    permission: Permission to reload BuildersReach.
    default: op
